services:
  # web:
  #   build:
  #     context: ./client
  #   restart: always
  #   environment:
  #     - NODE_ENV=development
  #     - WATCHPACK_POLLING=true
  #   ports:
  #     - "3000:3000"
  #   develop:
  #     watch:
  #       - path: ./client/src
  #         target: /app/src
  #         action: sync
  #       - path: ./client/package.json
  #         action: rebuild

  usersDB:
    image: mysql:latest
    restart: always
    container_name: usersDB
    environment:
      MYSQL_ROOT_PASSWORD: muskansinghvi
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: muskansinghvi
    ports:
      - "3306:3306"
    volumes:
      - users_data:/var/lib/mysql # Corrected path

  users-service:
    build:
      context: ./users
    restart: always
    container_name: users-service
    environment:
      DB_HOST: usersDB
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: muskansinghvi
      DB_NAME: users_db
    depends_on:
      - usersDB
      - rabbitmq
    ports:
      - "3001:3001"
    develop:
      watch:
        - path: ./users
          action: rebuild

  feed-stream-processor:
    build:
      context: ./feed-stream-processor
    restart: always
    container_name: feed-stream-processor
    depends_on:
      - rabbitmq
    ports:
      - "3002:3002"
    develop:
      watch:
        - path: ./feed-stream-processor
          action: rebuild

  posts-service:
    build:
      context: ./posts
    restart: always
    ports:
      - "3003:3003"
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=AKIAYS2NWTRY6O6BJZ4G
      - AWS_SECRET_ACCESS_KEY=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
    depends_on:
      - rabbitmq
    develop:
      watch:
        - path: ./posts
          action: rebuild

  feed-service:
    build:
      context: ./feed
    restart: always
    ports:
      - "3004:3004"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
    develop:
      watch:
        - path: ./feed
          action: rebuild

  followers-service:
    build:
      context: ./followers
    restart: always
    ports:
      - "3005:3005"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
    develop:
      watch:
        - path: ./followers
          action: rebuild

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: myrabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: jaysurya00
      RABBITMQ_DEFAULT_PASS: muskansinghvi
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  users_data:
  posts_data:
  rabbitmq_data:
  redis_data:
