services:
  web:
    build:
      context: ./client
    restart: always
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./client/src
          target: /app/src
          action: sync
        - path: ./client/package.json
          action: rebuild

  usersDB:
    image: mysql:latest
    restart: always
    container_name: usersDB
    environment:
      MYSQL_ROOT_PASSWORD: muskansinghvi
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: muskansinghvi
    ports:
      - "3306:3306"
    volumes:
      - users_data:/var/lib/mysql  # Corrected path

  users-service:
    build:
      context: ./users
    container_name: users-service
    environment:
      DB_HOST: usersDB
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: muskansinghvi
      DB_NAME: users_db
    depends_on:
      - usersDB
    ports:
      - "3001:3001"
    develop:
      watch:
        - path: ./users
          action: rebuild

volumes:
  users_data: